// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package demo;

public interface HelloWorldResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.HelloWorldResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
