// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package demo;

public interface HelloWorldRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.HelloWorldRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
